@extends('layout')

@section('title', "Condiciones de uso")

@section('content')

<div style= "text-align: justify" class="row justify-content-center">
        <div class="col-lg-4">
          <h3>Condiciones de uso</h3>
        </div>
        <div class="col-lg-4">
          <p>Se considera usuario del presente portal web cualquiera que acceda y lo utilice. La condición de usuario comporta la total aceptación de las condiciones establecidas en el presente Aviso Legal y en las especiales que puedan establecerse para determinados servicios y utilidades. Los usuarios adquieren el compromiso de ajustar su actuación a las mencionadas condiciones y a observar lo que se ha dispuesto por la normativa legal, así como las instrucciones y avisos que se ponen en su conocimiento.</p>
          <p>Cuando sea necesaria la utilización de una contraseña o nombre de usuario para acceder a algún contenido o servicio de este portal web, el usuario queda obligado a mantener en secreto y a hacer un uso diligente. En caso de pérdida o utilización negligente de la contraseña, el usuario responderá de la utilización que hayan podido realizar terceras personas.</p>

          <h4>Información actualizada y de calidad</h4>

          <p>MasterLOL, a través de su portal web, facilita información de interés general sobre el videojuego League Of Legends, cultura tecnológica, estrategias y en especial, información y gestiones propias de cada jugador de este extraordinario videojuego. La información facilitada es la vigente en el momento de su publicación.</p>
          <p>MasterLOL procura que esta información sea exacta y precisa, y procede a su actualización con la máxima celeridad posible, tratando de evitar errores y corrigiéndolos tan pronto como los detecta. No obstante, MasterLOL no puede garantizar la inexistencia de errores ni que el contenido de la información se encuentre permanentemente actualizado.</p>
          <p>MasterLOL podrá efectuar, en cualquier momento y sin necesidad de previo aviso, modificaciones, supresiones o actualizaciones de la información  publicada o podrá cambiar su configuración o presentación.</p>
          <p>El acceso al  portal Web y sus subdominios, así como el uso de la Información que contiene, son de la exclusiva responsabilidad del usuario. MasterLOL no es responsable de ningún perjuicio que pudiera derivarse de esos hechos, ni tampoco puede garantizar que el acceso no se vea interrumpido o que el contenido o software al que pueda accederse esté libre de error o de causar daño.</p>
          <p>La propiedad intelectual del contenido, información, gráficos, diseño, multimedia, aplicaciones, productos, servicios y cualquiera otro material de este portal web y sus subdominios es de MasterLOL, salvo que se especifique lo contrario. Queda, por lo tanto, prohibida su copia, reproducción, distribución, publicación, descarga, exhibición o transmisión en cualquier formato o medio, incluyendo medios electrónicos, mecánicos, reprográficos, de grabación o cualquiera otro, sin el permiso previo por escrito de MasterLOL y en su caso, del propietario del copyright o derechos de autor.</p>
          <p>Cualquier uso no autorizado de materiales contenidos en esta web puede vulnerar leyes de copyright, de registro de marcas, de derechos de propiedad intelectual, de privacidad, publicidad, y el resto de legislación sobre comunicación. Queda prohibida la utilización de los contenidos de este portal web con fines comerciales o publicitarios.</p>
          <p>Sus diseños gráficos y las informaciones y códigos que contiene son de titularidad de MasterLOL, salvo expresa indicación de una titularidad diferente, y están protegidos por la legislación sobre propiedad intelectual.</p>
          <p>Los usuarios de Internet que accedan en este portal web y sus subdominios  pueden visualizar la información contenida en el mismo y efectuar descargas o reproducciones privadas en su sistema informático; no obstante, tal autorización no llega a la cesión posterior a terceros de los elementos reproducidos ni su instalación en un servidor conectado en Internet o a una red local. Queda absolutamente prohibida la distribución, modificación, alteración, cesión, comunicación pública y cualquiera otro acto que no sea expresamente autorizado por MasterLOL.</p>
          <p>MasterLOL no es responsable de los contenidos situados fuera de su web, en los lugares web de terceros, a los que se pueda acceder por medio de enlaces situados en el lugar web de MasterLOL. Informamos que tales enlaces que aparecen en su web tan solos constituyen una información al usuario sobre la existencia de otras fuentes de información y servicios en Internet sobre las materias a que se refieren, donde el visitante podrá, si acaso, ampliar o complementar las datos ofrecidas en este web, advirtiendo expresamente que eso no supone una sugerencia, invitación o recomendación para la visita de tales lugares de destino y, por lo tanto, se declina toda la responsabilidad relativa al resultado obtenido a través de tales enlaces hipertextuales; en particular, el visitante declara conocer que MasterLOL no garantiza de ninguna manera las condiciones i/o correcta prestación de los servicios o la calidad de los productos ofrecidos a el usuario por un tercero.</p>
          <p>En el caso de espacios de opinión o foros abiertos en sus páginas web, MasterLOL no se obliga a controlar las opiniones o informaciones abocadas por los usuarios, pero se reserva el derecho a eliminar aquellas que puedan resultar contrarias a la legalidad vigente, especialmente cuando implican una vulneración de los derechos y libertades fundamentales, a los buenos usos y a los presentes términos y condiciones. MasterLOL no será responsable de posibles daños o perjuicios que se pudieran derivar de omisiones, interferencias, interrupciones, desconexiones o averías en el funcionamiento operativo de este sistema electrónico, motivadas por causas ajenas a MasterLOL, o como consecuencia de ajustes o problemas técnicos propios; así como tampoco de daños que puedan ser causados por virus informáticos y por terceras personas por medio de intromisiones ilegitimas fuera del control de MasterLOL.</p>
          <p>La información proporcionada en respuesta a cualquier consulta o petición de información tiene carácter meramente orientativo y en ningún caso resultará vinculante para la resolución de los procedimientos administrativos, los cuales se hallan estrictamente sujetos a las normas legales o reglamentarias que les sean de aplicación.</p>
          <p>En los contenidos publicados se incluyen enlaces a páginas de sitios web de terceros, fundamentalmente de otras Administraciones públicas, que se considera pueden ser de interés para los usuarios. MasterLOL no asume ninguna responsabilidad derivada de las conexiones o los contenidos de esos enlaces.</p>
        </div>

@endsection